manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: baduino
      url-base: https://github.com/baduino

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    
    # Charybdis 트랙볼/마우스 기능을 위한 필수 모듈
    - name: zmk-pmw3610-driver
      remote: baduino
      revision: main

  self:
    path: config