manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: charlyko
      url-base: https://github.com/charlyko
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # <--- v0.1을 반드시 main으로 바꿔야 합니다.
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: charlyko
      revision: main
  self:
    path: config
